version: 2.1
jobs:
   build:
     docker:
       - image: circleci/node:14.10.1
     steps:
       - checkout
       - run: yarn
       - run: CI=true yarn run build
workflows:
  version: 2
  build-and-lint:
    jobs:
      - build