version: 2.1
jobs:
   build:
     docker:
       - image: circleci/node:14.10.1
     steps:
       - checkout
       - run: yarn
       - run: CI=true yarn run build
   hithere:
     docker:
       - image: circleci/node:14.10.1
     steps:
       - checkout
       - run: echo "Hellloooo!"
workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - hithere
# version: 2.1
# orbs:
#   node: circleci/node@3.0.0
# workflows:
#   node-tests:
#     jobs:
#       - node/test
