
export const REQUEST_CURRENTUSER_PENDING = 'REQUEST_CURRENTUSER_PENDING';
export const REQUEST_CURRENTUSER_SUCCESS = 'REQUEST_CURRENTUSER_SUCCESS';
export const REQUEST_CURRENTUSER_FAILED = 'REQUEST_CURRENTUSER_FAILED';
